# Test with package import path
version: 2

before:
  hooks:
    - go mod download

builds:
  - id: igscraper
    main: igscraper/cmd/igscraper
    binary: igscraper
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64

archives:
  - format: tar.gz

release:
  disable: true