version: '3.8'

services:
  igscraper:
    build:
      context: .
      dockerfile: Dockerfile
    image: igscraper:latest
    container_name: igscraper
    
    # Environment variables for configuration
    environment:
      # Instagram credentials (use secrets in production)
      INSTAGRAM_USERNAME: ${INSTAGRAM_USERNAME:-}
      INSTAGRAM_PASSWORD: ${INSTAGRAM_PASSWORD:-}
      
      # Storage configuration
      IGSCRAPER_DOWNLOAD_DIR: /downloads
      IGSCRAPER_CONFIG_DIR: /config
      
      # Rate limiting configuration
      IGSCRAPER_RATE_LIMIT_REQUESTS: ${RATE_LIMIT_REQUESTS:-10}
      IGSCRAPER_RATE_LIMIT_WINDOW: ${RATE_LIMIT_WINDOW:-60s}
      
      # Retry configuration
      IGSCRAPER_MAX_RETRIES: ${MAX_RETRIES:-3}
      IGSCRAPER_RETRY_DELAY: ${RETRY_DELAY:-5s}
      
      # Logging configuration
      IGSCRAPER_LOG_LEVEL: ${LOG_LEVEL:-info}
      IGSCRAPER_LOG_FORMAT: ${LOG_FORMAT:-json}
      
      # Proxy configuration (optional)
      HTTP_PROXY: ${HTTP_PROXY:-}
      HTTPS_PROXY: ${HTTPS_PROXY:-}
      NO_PROXY: ${NO_PROXY:-}
    
    # Volume mounts
    volumes:
      # Mount local directories for persistent storage
      - ./downloads:/downloads
      - ./config:/config
      
      # Optional: Mount .env file for credentials
      # - ./.env:/config/.env:ro
    
    # Security options
    security_opt:
      - no-new-privileges:true
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 128M
    
    # Restart policy
    restart: unless-stopped
    
    # Network configuration
    networks:
      - igscraper-network
    
    # Command examples (uncomment one to use)
    # command: scrape --username targetuser --limit 50
    # command: auth login
    # command: config show

# Define network
networks:
  igscraper-network:
    driver: bridge

# Define volumes (optional - use for named volumes)
volumes:
  downloads:
    driver: local
  config:
    driver: local