# docker-compose.override.yml - Development overrides
version: '3.8'

services:
  igscraper:
    # Build from local source for development
    build:
      context: .
      dockerfile: Dockerfile
      target: builder  # Stop at builder stage for development
    
    # Mount source code for live development
    volumes:
      - .:/build:ro
      - go-modules:/go/pkg/mod
      - go-build-cache:/root/.cache/go-build
    
    # Development environment variables
    environment:
      # Enable debug logging
      IGSCRAPER_LOG_LEVEL: debug
      IGSCRAPER_LOG_FORMAT: text
      
      # Development mode
      IGSCRAPER_DEV_MODE: "true"
      
      # Disable rate limiting for development
      IGSCRAPER_RATE_LIMIT_REQUESTS: 1000
      IGSCRAPER_RATE_LIMIT_WINDOW: 1s
    
    # Override entrypoint for development
    entrypoint: ["/bin/sh"]
    command: ["-c", "go run ./cmd/igscraper"]
    
    # Keep container running for debugging
    stdin_open: true
    tty: true

# Named volumes for caching
volumes:
  go-modules:
    driver: local
  go-build-cache:
    driver: local